#!/usr/bin/env bash
set -euo pipefail

# 激进 CMT 版 hMOF 重新预训练脚本。
# 设计思路：
# 1. 这是独立实验脚本，不改公共默认参数。
# 2. 形状尽量向 CMT 靠拢，但保持和原版 MOFTransformer 更可比：
#    - hid_dim 保持 384，不靠单纯堆宽度取胜
#    - img_size 选 25，既比 20 更大，又满足 patch_size=5 的整除要求
#    - 图分支仍然控制在单张 A6000 更稳的范围内
# 3. fresh pretrain，从头重新训，不加载之前的小模型 ckpt。
# 4. 四任务继续保留，但这版按“孔径+化学并重”来分配预算：
#    - ggm 只保留少量稳定约束
#    - mpp 保留通用表征学习能力
#    - chem / zeopp 明显抬高，优先服务吸附相关下游

ROOT="/home/yihaoyu/docker/bag/MOFTransformer_CMT"
SCRIPT="$ROOT/MOFTransformer/pretrain_alignn_hmof.py"
LOG_DIR="$ROOT/logs"
PID_DIR="$ROOT/pids"
mkdir -p "$LOG_DIR"
mkdir -p "$PID_DIR"

TIMESTAMP="$(date +%Y%m%d_%H%M%S)"
LOG_FILE="$LOG_DIR/pretrain_alignn_hmof_1pct_cmt_aggressive_${TIMESTAMP}.log"
PID_FILE="$PID_DIR/pretrain_alignn_hmof_1pct_cmt_aggressive_${TIMESTAMP}.pid"

PYTHON_BIN="${PYTHON_BIN:-python}"
CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-GPU-4c457a8a-39a3-5346-1f3c-5993b3102d03}"

ALIGNN_PRETRAIN_ROOT_DATASET="${ALIGNN_PRETRAIN_ROOT_DATASET:-/home/yihaoyu/docker/bag/MOFTransformer_upgrade/MOFTransformer/hmof_pretrain_GGM_MPP_1pct}"
ALIGNN_PRETRAIN_LOG_DIR="${ALIGNN_PRETRAIN_LOG_DIR:-/home/yihaoyu/docker/bag/MOFTransformer_CMT/outputs/hmof_pretrain_GGM_MPP_1pct/logs_alignn_pretrain_cmt_aggressive}"
ALIGNN_PRETRAIN_EXP_NAME="${ALIGNN_PRETRAIN_EXP_NAME:-alignn_hmof_pretrain_1pct_cmt_aggressive}"

ALIGNN_PRETRAIN_MAX_EPOCHS="${ALIGNN_PRETRAIN_MAX_EPOCHS:-30}"
ALIGNN_PRETRAIN_PER_GPU_BATCHSIZE="${ALIGNN_PRETRAIN_PER_GPU_BATCHSIZE:-1}"
ALIGNN_PRETRAIN_BATCH_SIZE="${ALIGNN_PRETRAIN_BATCH_SIZE:-4}"
ALIGNN_PRETRAIN_NUM_WORKERS="${ALIGNN_PRETRAIN_NUM_WORKERS:-4}"
ALIGNN_PRETRAIN_PRECISION="${ALIGNN_PRETRAIN_PRECISION:-16-mixed}"

ALIGNN_PRETRAIN_MAX_GRAPH_LEN="${ALIGNN_PRETRAIN_MAX_GRAPH_LEN:-320}"
ALIGNN_PRETRAIN_HID_DIM="${ALIGNN_PRETRAIN_HID_DIM:-384}"
ALIGNN_PRETRAIN_NUM_LAYERS="${ALIGNN_PRETRAIN_NUM_LAYERS:-8}"
ALIGNN_PRETRAIN_NUM_HEADS="${ALIGNN_PRETRAIN_NUM_HEADS:-8}"
ALIGNN_PRETRAIN_MLP_RATIO="${ALIGNN_PRETRAIN_MLP_RATIO:-4}"
ALIGNN_PRETRAIN_ALIGNN_LAYERS="${ALIGNN_PRETRAIN_ALIGNN_LAYERS:-2}"
ALIGNN_PRETRAIN_IMG_SIZE="${ALIGNN_PRETRAIN_IMG_SIZE:-25}"
ALIGNN_PRETRAIN_NBR_FEA_LEN="${ALIGNN_PRETRAIN_NBR_FEA_LEN:-64}"

ALIGNN_PRETRAIN_LR="${ALIGNN_PRETRAIN_LR:-6e-5}"
ALIGNN_PRETRAIN_WEIGHT_DECAY="${ALIGNN_PRETRAIN_WEIGHT_DECAY:-1e-2}"
ALIGNN_PRETRAIN_DROP_RATE="${ALIGNN_PRETRAIN_DROP_RATE:-0.1}"
ALIGNN_PRETRAIN_GRAPH_DROPOUT="${ALIGNN_PRETRAIN_GRAPH_DROPOUT:-0.1}"
ALIGNN_PRETRAIN_MPP_RATIO="${ALIGNN_PRETRAIN_MPP_RATIO:-0.20}"

ALIGNN_PRETRAIN_GGM_WEIGHT="${ALIGNN_PRETRAIN_GGM_WEIGHT:-0.1}"
ALIGNN_PRETRAIN_MPP_WEIGHT="${ALIGNN_PRETRAIN_MPP_WEIGHT:-0.4}"
ALIGNN_PRETRAIN_CHEM_WEIGHT="${ALIGNN_PRETRAIN_CHEM_WEIGHT:-0.6}"
ALIGNN_PRETRAIN_ZEOPP_WEIGHT="${ALIGNN_PRETRAIN_ZEOPP_WEIGHT:-0.9}"

ALIGNN_PRETRAIN_CHEM_LABEL_PATH="${ALIGNN_PRETRAIN_CHEM_LABEL_PATH:-/home/yihaoyu/docker/bag/MOFTransformer_CMT/generated_labels/hmof_1pct_chem/chem_labels.csv}"
ALIGNN_PRETRAIN_ZEOPP_LABEL_PATH="${ALIGNN_PRETRAIN_ZEOPP_LABEL_PATH:-/home/yihaoyu/docker/bag/MOFTransformer_CMT/generated_labels/hmof_1pct_zeopp/zeopp_labels.csv}"
ALIGNN_PRETRAIN_CHEM_LABEL_NAMES="${ALIGNN_PRETRAIN_CHEM_LABEL_NAMES:-density,metal_fraction,fraction_C,fraction_N,fraction_O}"
ALIGNN_PRETRAIN_ZEOPP_LABEL_NAMES="${ALIGNN_PRETRAIN_ZEOPP_LABEL_NAMES:-pld,lcd,av_fraction,nav_fraction}"

if command -v stdbuf >/dev/null 2>&1; then
  BUFFER_CMD=(stdbuf -oL -eL)
else
  BUFFER_CMD=()
fi

nohup setsid env \
  PYTHONUNBUFFERED=1 \
  PYTORCH_CUDA_ALLOC_CONF="max_split_size_mb:128,garbage_collection_threshold:0.9" \
  CUDA_VISIBLE_DEVICES="$CUDA_VISIBLE_DEVICES" \
  ALIGNN_PRETRAIN_ROOT_DATASET="$ALIGNN_PRETRAIN_ROOT_DATASET" \
  ALIGNN_PRETRAIN_LOG_DIR="$ALIGNN_PRETRAIN_LOG_DIR" \
  ALIGNN_PRETRAIN_EXP_NAME="$ALIGNN_PRETRAIN_EXP_NAME" \
  ALIGNN_PRETRAIN_MAX_EPOCHS="$ALIGNN_PRETRAIN_MAX_EPOCHS" \
  ALIGNN_PRETRAIN_PER_GPU_BATCHSIZE="$ALIGNN_PRETRAIN_PER_GPU_BATCHSIZE" \
  ALIGNN_PRETRAIN_BATCH_SIZE="$ALIGNN_PRETRAIN_BATCH_SIZE" \
  ALIGNN_PRETRAIN_NUM_WORKERS="$ALIGNN_PRETRAIN_NUM_WORKERS" \
  ALIGNN_PRETRAIN_PRECISION="$ALIGNN_PRETRAIN_PRECISION" \
  ALIGNN_PRETRAIN_MAX_GRAPH_LEN="$ALIGNN_PRETRAIN_MAX_GRAPH_LEN" \
  ALIGNN_PRETRAIN_HID_DIM="$ALIGNN_PRETRAIN_HID_DIM" \
  ALIGNN_PRETRAIN_NUM_LAYERS="$ALIGNN_PRETRAIN_NUM_LAYERS" \
  ALIGNN_PRETRAIN_NUM_HEADS="$ALIGNN_PRETRAIN_NUM_HEADS" \
  ALIGNN_PRETRAIN_MLP_RATIO="$ALIGNN_PRETRAIN_MLP_RATIO" \
  ALIGNN_PRETRAIN_ALIGNN_LAYERS="$ALIGNN_PRETRAIN_ALIGNN_LAYERS" \
  ALIGNN_PRETRAIN_IMG_SIZE="$ALIGNN_PRETRAIN_IMG_SIZE" \
  ALIGNN_PRETRAIN_NBR_FEA_LEN="$ALIGNN_PRETRAIN_NBR_FEA_LEN" \
  ALIGNN_PRETRAIN_LR="$ALIGNN_PRETRAIN_LR" \
  ALIGNN_PRETRAIN_WEIGHT_DECAY="$ALIGNN_PRETRAIN_WEIGHT_DECAY" \
  ALIGNN_PRETRAIN_DROP_RATE="$ALIGNN_PRETRAIN_DROP_RATE" \
  ALIGNN_PRETRAIN_GRAPH_DROPOUT="$ALIGNN_PRETRAIN_GRAPH_DROPOUT" \
  ALIGNN_PRETRAIN_MPP_RATIO="$ALIGNN_PRETRAIN_MPP_RATIO" \
  ALIGNN_PRETRAIN_GGM_WEIGHT="$ALIGNN_PRETRAIN_GGM_WEIGHT" \
  ALIGNN_PRETRAIN_MPP_WEIGHT="$ALIGNN_PRETRAIN_MPP_WEIGHT" \
  ALIGNN_PRETRAIN_CHEM_WEIGHT="$ALIGNN_PRETRAIN_CHEM_WEIGHT" \
  ALIGNN_PRETRAIN_ZEOPP_WEIGHT="$ALIGNN_PRETRAIN_ZEOPP_WEIGHT" \
  ALIGNN_PRETRAIN_CHEM_LABEL_PATH="$ALIGNN_PRETRAIN_CHEM_LABEL_PATH" \
  ALIGNN_PRETRAIN_ZEOPP_LABEL_PATH="$ALIGNN_PRETRAIN_ZEOPP_LABEL_PATH" \
  ALIGNN_PRETRAIN_CHEM_LABEL_NAMES="$ALIGNN_PRETRAIN_CHEM_LABEL_NAMES" \
  ALIGNN_PRETRAIN_ZEOPP_LABEL_NAMES="$ALIGNN_PRETRAIN_ZEOPP_LABEL_NAMES" \
  "${BUFFER_CMD[@]}" \
  "$PYTHON_BIN" -u "$SCRIPT" \
  >> "$LOG_FILE" 2>&1 < /dev/null &

PID=$!
echo "$PID" > "$PID_FILE"
disown "$PID" 2>/dev/null || true

echo "started ALIGNN hMOF pretraining (aggressive CMT profile) in background"
echo "pid: $PID"
echo "pid_file: $PID_FILE"
echo "cuda_visible_devices: $CUDA_VISIBLE_DEVICES"
echo "root_dataset: $ALIGNN_PRETRAIN_ROOT_DATASET"
echo "log_dir: $ALIGNN_PRETRAIN_LOG_DIR"
echo "exp_name: $ALIGNN_PRETRAIN_EXP_NAME"
echo "shape: hid=$ALIGNN_PRETRAIN_HID_DIM layers=$ALIGNN_PRETRAIN_NUM_LAYERS heads=$ALIGNN_PRETRAIN_NUM_HEADS alignn=$ALIGNN_PRETRAIN_ALIGNN_LAYERS img=$ALIGNN_PRETRAIN_IMG_SIZE max_graph_len=$ALIGNN_PRETRAIN_MAX_GRAPH_LEN"
echo "optimizer: lr=$ALIGNN_PRETRAIN_LR wd=$ALIGNN_PRETRAIN_WEIGHT_DECAY drop=$ALIGNN_PRETRAIN_DROP_RATE graph_drop=$ALIGNN_PRETRAIN_GRAPH_DROPOUT"
echo "tasks: ggm=$ALIGNN_PRETRAIN_GGM_WEIGHT mpp=$ALIGNN_PRETRAIN_MPP_WEIGHT chem=$ALIGNN_PRETRAIN_CHEM_WEIGHT zeopp=$ALIGNN_PRETRAIN_ZEOPP_WEIGHT mpp_ratio=$ALIGNN_PRETRAIN_MPP_RATIO"
echo "log: $LOG_FILE"
echo "follow log with:"
echo "tail -f $LOG_FILE"
